export const players = [
  {
    id: 1,
    name: "Arjun Sharma",
    role: "Opening Batsman",
    age: 24,
    matches: 48,
    runs: 1842,
    average: 41.8,
    image: null,
    bio: "Aggressive opener with a penchant for boundaries. Arjun has been the cornerstone of Dcorp's batting lineup for 3 seasons.",
  },
  {
    id: 2,
    name: "Rahul Mehta",
    role: "Fast Bowler",
    age: 26,
    matches: 52,
    wickets: 87,
    economy: 4.2,
    image: null,
    bio: "Rapid seam bowler who consistently troubles opposition batsmen with late swing and sharp bouncers.",
  },
  {
    id: 3,
    name: "Vikram Patel",
    role: "All-Rounder",
    age: 28,
    matches: 60,
    runs: 1120,
    wickets: 54,
    image: null,
    bio: "The engine of the team. Vikram contributes with bat and ball and leads the fielding unit with energy.",
  },
  {
    id: 4,
    name: "Kiran Singh",
    role: "Wicket-Keeper Batsman",
    age: 22,
    matches: 34,
    runs: 890,
    dismissals: 41,
    image: null,
    bio: "Lightning reflexes behind the stumps and a reliable lower-order bat. Kiran's glove work is second to none.",
  },
  {
    id: 5,
    name: "Deepak Nair",
    role: "Spin Bowler",
    age: 30,
    matches: 65,
    wickets: 112,
    economy: 3.8,
    image: null,
    bio: "Crafty left-arm spinner who turns the ball sharply on any surface. The most experienced member of our squad.",
  },
  {
    id: 6,
    name: "Anil Kumar",
    role: "Middle-Order Batsman",
    age: 25,
    matches: 44,
    runs: 1340,
    average: 35.3,
    image: null,
    bio: "Solid technique with an ability to anchor the innings. Anil thrives under pressure and delivers when it matters most.",
  },
];

export const fixtures = [
  {
    id: 1,
    opponent: "Riverside CC",
    date: "2026-04-12",
    time: "10:00 AM",
    venue: "Greenfield Park Ground",
    type: "League",
    status: "upcoming",
  },
  {
    id: 2,
    opponent: "Northside XI",
    date: "2026-04-19",
    time: "09:30 AM",
    venue: "Northside Sports Complex",
    type: "Cup",
    status: "upcoming",
  },
  {
    id: 3,
    opponent: "City Thunder CC",
    date: "2026-04-26",
    time: "10:00 AM",
    venue: "Greenfield Park Ground",
    type: "League",
    status: "upcoming",
  },
  {
    id: 4,
    opponent: "Sunrisers CC",
    date: "2026-05-03",
    time: "10:00 AM",
    venue: "Sunrisers Oval",
    type: "Friendly",
    status: "upcoming",
  },
];

export const results = [
  {
    id: 1,
    opponent: "Westfield Warriors",
    date: "2026-03-29",
    venue: "Greenfield Park Ground",
    type: "League",
    dcorpScore: "187/6",
    opponentScore: "162/9",
    result: "won",
    motm: "Arjun Sharma (72 runs)",
  },
  {
    id: 2,
    opponent: "Eastbourne CC",
    date: "2026-03-15",
    venue: "Eastbourne Ground",
    type: "Cup",
    dcorpScore: "145/10",
    opponentScore: "146/4",
    result: "lost",
    motm: "Deepak Nair (4/28)",
  },
  {
    id: 3,
    opponent: "Hillside CC",
    date: "2026-03-08",
    venue: "Greenfield Park Ground",
    type: "League",
    dcorpScore: "220/5",
    opponentScore: "198/8",
    result: "won",
    motm: "Vikram Patel (55 runs, 3/32)",
  },
  {
    id: 4,
    opponent: "Lakeside Lions",
    date: "2026-02-28",
    venue: "Lakeside Oval",
    type: "League",
    dcorpScore: "178/7",
    opponentScore: "177/9",
    result: "won",
    motm: "Rahul Mehta (4/22)",
  },
];

export const news = [
  {
    id: 1,
    title: "Dcorp CC Wins Spring League Opener in Thrilling Fashion",
    date: "2026-03-30",
    category: "Match Report",
    excerpt:
      "Arjun Sharma's magnificent 72 off 58 balls guided Dcorp Cricket Club to a 25-run victory over Westfield Warriors in the Spring League opener at Greenfield Park.",
    content:
      "In a nail-biting encounter at Greenfield Park Ground, Dcorp Cricket Club kicked off their Spring League campaign with a commanding 25-run victory over Westfield Warriors. Arjun Sharma set the tone with an aggressive 72 off 58 balls, hitting 8 fours and 3 sixes. The bowlers then put in a disciplined performance to restrict Warriors to 162/9, sealing a memorable win.",
  },
  {
    id: 2,
    title: "Club Announces New Training Schedule for 2026 Season",
    date: "2026-03-20",
    category: "Club News",
    excerpt:
      "Dcorp CC has unveiled an enhanced training program for the 2026 season, with sessions every Tuesday and Thursday evening at Greenfield Park.",
    content:
      "Dcorp Cricket Club is delighted to announce an upgraded training program for the 2026 season. Training sessions will be held every Tuesday and Thursday from 6:30 PM at Greenfield Park. The club has also brought in specialist batting and bowling coaches to help players reach their full potential. New members are welcome to attend a free trial session.",
  },
  {
    id: 3,
    title: "Talent Hunt: Dcorp CC Looking for Young Cricketers",
    date: "2026-03-10",
    category: "Recruitment",
    excerpt:
      "We are actively scouting talented cricketers in the area. If you are passionate about cricket and want to be part of a growing club, we want to hear from you.",
    content:
      "Dcorp Cricket Club is expanding its roster and is on the lookout for talented players of all skill levels. Whether you're an experienced cricketer or just starting out, we provide a supportive environment to grow. Our upcoming talent trials will be held on April 5th at Greenfield Park. Register via the Join Us page on our website.",
  },
  {
    id: 4,
    title: "Greenfield Park Ground Upgrades Complete",
    date: "2026-02-25",
    category: "Club News",
    excerpt:
      "Our home ground at Greenfield Park has received a major upgrade, including improved pitch maintenance, new sight screens, and upgraded changing facilities.",
    content:
      "We are thrilled to announce the completion of major upgrades to our home ground at Greenfield Park. The improvements include professional pitch maintenance and preparation, two new sight screens for better visibility, fully refurbished changing rooms, and new spectator seating. These upgrades reflect our commitment to providing the best facilities for our players and supporters.",
  },
];
